# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='text',
            new_name='items',
        ),
    ]
