# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160517_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('trueVotes', models.IntegerField(default=0)),
                ('falseVotes', models.IntegerField(default=0)),
                ('itemlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.ItemList')),
            ],
        ),
    ]
