# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20160517_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcomparison',
            old_name='item_text',
            new_name='comparison_text',
        ),
        migrations.AddField(
            model_name='itemcomparison',
            name='item1_id',
            field=models.IntegerField(default=-1),
        ),
    ]
