# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_itemcomparison_item2_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.ItemList')),
            ],
        ),
    ]
