# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_listmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('item_id', models.IntegerField(default=-1)),
                ('item_rank', models.IntegerField(default=-1)),
                ('itemlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.ItemList')),
            ],
        ),
    ]
