# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20160518_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmanager',
            old_name='manager_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='itemlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.ItemList'),
        ),
    ]
