# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20160518_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmanager',
            name='itemlist',
        ),
        migrations.RenameField(
            model_name='itemlist',
            old_name='items',
            new_name='list_text',
        ),
        migrations.AddField(
            model_name='itemlist',
            name='madeItemDict',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ListManager',
        ),
    ]
