# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_remove_itemcomparison_comparison_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomparison',
            name='item1_id',
        ),
        migrations.RemoveField(
            model_name='itemcomparison',
            name='item2_id',
        ),
        migrations.AddField(
            model_name='itemcomparison',
            name='item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemcomparison_item1s', to='vote.Item'),
        ),
        migrations.AddField(
            model_name='itemcomparison',
            name='item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemcomparison_item2s', to='vote.Item'),
        ),
    ]
