# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20160518_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomparison',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcomparison_item1s', to='vote.Item'),
        ),
        migrations.AlterField(
            model_name='itemcomparison',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemcomparison_item2s', to='vote.Item'),
        ),
    ]
